manifestVersion = 0

[package]
  type = "mod"
  name = "npcvariety"
  description = "A Fabric mod that gives villagers a bigger variety of skins"
  version = "1.2.5"
  platform = "fabric"
  license = "ARR"
  source = "https://github.com/OverlordsIII/NPCVarietyPort"
  homepage = "https://www.curseforge.com/minecraft/mc-mods/npc-variety-port"
  author = "Mister_Crabman, OverlordsIII, YumatanGames"

[requirements]
  minecraft = "~1.16.2"
  fabric = ">=0.7.4"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
  [dev.dependencies]
    test-mansion = "*"
